accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('profile/update', views.UserProfileView.as_view(), name='profile_update'),
]

mp3/urls.py
from django.urls import path
from . import views


app_name = 'mp3'

urlpatterns = [
    path('', views.AlbumList.as_view(), name='album_list'),
    path('<slug:slug>/', views.AlbumDetail.as_view(), name='album_detail'),
    path('album/add/', views.AlbumCreate.as_view(), name='add_album'),
    path('album/<slug:slug>/', views.AlbumUpdate.as_view(), name='update_album'),
    path('album/<slug:slug>/delete', views.AlbumDelete.as_view(), name='delete_album'),
    path('songs/', views.SongList.as_view(), name='song_list'),
    path('song/<slug:slug>/add/', views.SongCreate.as_view(), name='add_song'),
    path('song/<slug:slug>/delete', views.SongDelete.as_view(), name='delete_song'),
]

nwaben/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic import TemplateView
from nwaben.views import ContactView

urlpatterns = [
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('burial_memories/', include('burial_memories.urls', namespace='burial_memories')),
    path('about/', ContactView.as_view(), name='about'),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),
    # path('archives/', include('archive.urls', namespace='archives')),
    path('mp3/', include('mp3.urls', namespace='mp3')),
    path('search/', include('search.urls', namespace='search')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('summernote/', include('django_summernote.urls')),
]

# urlpatterns += staticfiles_urlpatterns()
# # Remove this conditional check if you want to upload to Heroku
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# administrator backend service url
urlpatterns += [
    path('admin-family-nwaben/', admin.site.urls),
]

# Url to catch any un-matched pattern and render 404
urlpatterns += [re_path(r'^.*.', TemplateView.as_view(template_name='404.html'), name='404_')]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager,
    AbstractBaseUser,
    PermissionsMixin
)

from phonenumber_field.modelfields import PhoneNumberField

from nwaben.storage_backends import PublicMediaStorage

GENDER_CHOICE = (("Male", "Male"), ("Female", "Female"))


def upload_dir(instance, filename):
    return "{}/{}".format(instance.username, filename)


class UserManager(BaseUserManager):

    def create_user(self, email, username, phone=None, gender=None, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        elif not phone:
            raise ValueError('Pls provide your mobile number eg: +234080312345678')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            phone=phone,
            gender=gender,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, phone, gender, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            username,
            phone,
            gender,
            password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)
    bio = models.CharField(max_length=240, blank=True, default="")
    avatar = models.ImageField(storage=PublicMediaStorage(), upload_to=upload_dir, null=True, blank=True, help_text="You profile image")
    phone = PhoneNumberField()
    gender = models.CharField(max_length=6, choices=GENDER_CHOICE, blank=True, null=True)
    follow_count = models.PositiveIntegerField(default=0)
    date_joined = models.DateTimeField(auto_now_add=True, )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username', 'phone', 'gender']

    def __str__(self):
        return "{}".format(self.username)

    @property
    def image_url(self):
        if self.avatar:
            return self.avatar.url
        else:
            return 'https://res.cloudinary.com/geetechlab-com/image/upload/v1583147406/nwaben.com/user_azjdde_sd2oje' \
                   '.jpg '

    def get_full_name(self):
        # The user is identified by their
        return self.username

    def get_short_name(self):
        # The user is identified by their
        return "{} ({})".format(self.username, self.email)

accounts/forms.py
from .models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "phone", "gender", "password1", "password2")
        model = User

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({'placeholder': 'username'})
        self.fields["email"].widget.attrs.update({'placeholder': 'example@email.com'})
        self.fields["phone"].widget.attrs.update({'placeholder': '+234801234567'})
        self.fields["gender"].widget.attrs.update({'placeholder': 'select gender'})
        self.fields["password1"].widget.attrs.update({'placeholder': 'password'})
        self.fields["password2"].widget.attrs.update({'placeholder': 'confirm password'})

        self.fields["username"].label = ""
        self.fields["email"].label = ""
        self.fields["phone"].label = ""
        self.fields["gender"].label = ""
        self.fields["password1"].label = ""
        self.fields["password2"].label = ""
        self.fields["password1"].help_text = ""
        self.fields["password2"].help_text = ""


class UserChangeForm(UserChangeForm):
    class Meta:
        fields = ("avatar", "bio", "phone")
        model = User

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect

from .models import User
from .forms import UserChangeForm
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views import generic, View

from accounts import forms


class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy("home")
    template_name = "accounts/login.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    # Takes users to success_url if the login...
    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)


class LogoutView(generic.RedirectView):
    url = reverse_lazy("home")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


# The default django signup form uses only username tp log users
# if you want to use email, then create form.py
class SignupView(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/register.html"


class UpdateUserProfileView(generic.UpdateView ):
    template_name = 'accounts/update_profile.html'
    model = User
    form_class = UserChangeForm
    fields = ["avatar", "bio"]
    success_url = reverse_lazy('profile')


class UserProfileView(generic.DetailView, generic.UpdateView):
    template_name = "accounts/profile.html"
    model = User
    fields = ["avatar", "bio"]
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

accounts/templates/accounts/login.html
{% extends 'layout.html' %}

{% block title %}login{% endblock %}

{% block content %}
<div class="login-page full-screen sidebar-collapse">
  <div class="wrapper">
    <div class="page-header" style="background-image: url('https://res.cloudinary.com/geetechlab-com/image/upload/v1612913404/nwaben.com/concert-768722_1280_mptdmy.jpg');">
      <div class="filter"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-6 col-sm-6 ml-auto mr-auto">
            <div class="card card-register">
              <h3 class="card-title">Welcome</h3>
              <form class="register-form" method="post">
                {% csrf_token %}
                {% include 'includes/form.html' %}
                  <button class="btn btn-block btn-round" type="submit">Login</button>
              </form>
              <div class="forgot">
                <a href="..." class="btn btn-link btn-danger">Forgot password?</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-link btn-danger">Register</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'layout.html' %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<div class="profile-page sidebar-collapse">
  <div class="page-header page-header-small" style="background-image: url('https://res.cloudinary.com/geetechlab-com/image/upload/v1612913404/nwaben.com/guitar-1699501_1280_meb3ry.jpg');">
    <div class="filter"></div>
  </div>
  <div class="wrapper">
    <div class="profile-content section">
      <div class="container">
        <div class="row">
          <div class="profile-picture">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new img-no-padding">
                <img src="{{ user.image_url }}" alt="{{ user.username }}">
              </div>
              <div class="name">
                <h4 class="title text-center">{{ user.get_full_name }}
                  <br />
                    {% if user.gender %}
                        <small>Gender : {{ user.gender }}</small>
                    {% else %}
                        <small>No Gender yet</small>
                    {% endif %}
                </h4>
              </div>
            </div>
          </div>
        </div>
        <br/>
        <div class="nav-tabs-navigation">
          <div class="nav-tabs-wrapper">
            <ul class="nav nav-tabs" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#details" role="tab">Details</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#update_details" role="tab">Update my details</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane active" id="details" role="tabpanel">
            <div class="row">
                <div class="info">
                    <div class="description">
                        {% if user.bio %}
                            <p>{{ user.bio }}</p>
                        {% else %}
                            <h4 class="info-title">Tell us about your self.</h4>
                            <p>Example: About your previous achievements, your family, what you are currently doing and your current location</p>
                        {% endif %}
                        <br>
                        <hr width="50%">
                          <p>My contacts</p>
                          <small>{{ user.phone }}</small>
                          <br>
                          <small>{{ user.email }}</small>
                    </div>
                </div>
            </div>
          </div>
          <div class="tab-pane text-center" id="update_details" role="tabpanel">
            <div class="col-md-6 ml-auto mr-auto text-center">
                {% include "accounts/update_profile.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}register{% endblock %}

{% block content %}
<div class="register-page full-screen sidebar-collapse">
  <div class="wrapper">
    <div class="page-header" style="background-image: url('https://res.cloudinary.com/geetechlab-com/image/upload/v1612913404/nwaben.com/concert-768722_1280_mptdmy.jpg');">
      <div class="filter"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-7 col-12 ml-auto">
            <div class="info info-horizontal">
              <div class="icon">
                <i class="fa fa-umbrella"></i>
              </div>
              <div class="description">
                <h3> We've got you covered </h3>
                <p>Larger, yet dramatically thinner. More powerful, but remarkably power efficient. Everything you need in a single case.</p>
              </div>
            </div>
            <div class="info info-horizontal">
              <div class="icon">
                <i class="fa fa-map-signs"></i>
              </div>
              <div class="description">
                <h3> Clear Directions </h3>
                <p>Efficiently unleash cross-media information without cross-media value. Quickly maximize timely deliverables for real-time schemas.</p>
              </div>
            </div>
            <div class="info info-horizontal">
              <div class="icon">
                <i class="fa fa-user-secret"></i>
              </div>
              <div class="description">
                <h3> We value your privacy </h3>
                <p>Completely synergize resource taxing relationships via premier niche markets.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-5 col-12 mr-auto">
            <div class="card card-register">
              <h3 class="card-title text-center">Register</h3>
              <form class="register-form" method="post">
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button class="btn btn-block btn-round" type="submit">Register</button>
              </form>
              <div class="login">
                <p>Already have an account?
                  <a href="{% url 'accounts:login' %}">Login</a>.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/update_profile.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button class="btn btn-rotate btn-round" type="submit"><i class="fa fa-cog"></i>update profile</button>
</form>