mp3/urls.py
from django.urls import path
from . import views


app_name = 'mp3'

urlpatterns = [
    path('', views.AlbumList.as_view(), name='album_list'),
    path('<slug:slug>/', views.AlbumDetail.as_view(), name='album_detail'),
    path('album/add/', views.AlbumCreate.as_view(), name='add_album'),
    path('album/<slug:slug>/', views.AlbumUpdate.as_view(), name='update_album'),
    path('album/<slug:slug>/delete', views.AlbumDelete.as_view(), name='delete_album'),
    path('songs/', views.SongList.as_view(), name='song_list'),
    path('song/<slug:slug>/add/', views.SongCreate.as_view(), name='add_song'),
    path('song/<slug:slug>/delete', views.SongDelete.as_view(), name='delete_song'),
]

mp3/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils.text import slugify

from nwaben.storage_backends import PrivateMediaStorage, PublicMediaStorage
from .validators import validate_file_extension


class Album(models.Model):
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    artist = models.CharField(max_length=250)
    album_name = models.CharField(max_length=255)
    album_detail = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField()
    owned_by = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      blank=True, related_name='owned_by')
    price = models.DecimalField(max_digits=9, decimal_places=2)
    genre = models.CharField(max_length=100)
    album_logo = models.ImageField(upload_to='album/covers', blank=True, null=True)
    date_uploaded = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Albums"
        ordering = ('-date_uploaded',)
        unique_together = ["album_name"]

    def __str__(self):
        return "{}".format(self.album_name)

    def get_absolute_url(self):
        return reverse('mp3:album_detail', kwargs={'slug': self.slug})

    @property
    def image_url(self):
        if self.album_logo:
            return self.album_logo.url
        return 'https://res.cloudinary.com/geetechlab-com/image/upload/c_scale,h_159,q_42/v1597153444/nfivbpcanbr8s6mjn2uy.png'

    def album_songs(self):
        album_obj = Album.objects.get(slug=self.slug)
        return album_obj.song_set.count()


# def album_post_save_signal(instance, *args, **kwargs):
#     if instance.uploaded_by:
#         instance.owned_by.add(instance.uploaded_by)
#
#
# post_save.connect(album_post_save_signal, sender=Album)


def album_pre_save_signal(sender, instance, *args, **kwargs):
    if not instance.slug:
        new_slug = "{}-{}".format(instance.album_name, instance.artist)
        print(instance.pk)
        try:
            instance.slug = slugify(instance.album_name)
        except Album.DoesNotExist:
            instance.slug = instance.slug
        except Album.MultipleObjectsReturned:
            instance.slug = slugify(new_slug)


pre_save.connect(album_pre_save_signal, sender=Album)


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=225)
    slug = models.SlugField()
    audio_file = models.FileField(storage=PublicMediaStorage(),
                                  upload_to='album/songs',
                                  blank=True,
                                  null=True,
                                  max_length=200,
                                  validators=[validate_file_extension])

    class Meta:
        verbose_name = 'Song'
        verbose_name_plural = 'Songs'

    def __str__(self):
        return "{}".format(self.song_title)

    def get_absolute_url(self):
        return reverse('mp3:album_detail', kwargs={'slug': self.slug})


def song_pre_save_signal(sender, instance, *args, **kwargs):
    if not instance.slug:
        new_slug = "{}-{}".format(instance.song_title, instance.pk)
        try:
            instance.slug = slugify(instance.song_title)
        except Song.DoesNotExist:
            instance.slug = instance.slug
        except Song.MultipleObjectsReturned:
            instance.slug = slugify(new_slug)
    # elif not instance.song_token:
    #     instance.song_token = instance.album.album_token


pre_save.connect(song_pre_save_signal, sender=Song)

mp3/forms.py
from django import forms
from .models import Album, Song


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['artist', 'album_name', 'price', 'genre', 'album_logo']


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']

mp3/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from accounts.models import User
from mp3 import paystack
from nwaben import settings
from .forms import SongForm
from .models import Album, Song


class AlbumList(ListView):
    model = Album
    template_name = 'mp3/album_list.html'
    context_object_name = 'albums'


class AlbumDetail(DetailView):
    model = Album
    template_name = 'mp3/album_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumDetail, self).get_context_data(**kwargs)
        context['songs'] = self.get_object().song_set.all().order_by('-song_title')
        context['key'] = paystack.PAYSTACK_PUBLIC_KEY
        context['current_user'] = self.request.user
        # context['songs_count'] = context['songs'].count()
        instance = Album.objects.get(album_name=self.get_object())
        if self.request.user in instance.owned_by.all():
            print(True)
        return context

    def post(self, *args, **kwargs):
        paid_user_str = self.request.POST.get('paid_user')
        paid_user = User.objects.get(username=paid_user_str)
        album_name = self.request.POST.get('album_name')
        paid_album = Album.objects.get(album_name=album_name)
        paid_album.owned_by.add(paid_user)
        paid_album.save()
        return JsonResponse({'message': 'Payment successful'}, status=201)

    def get_success_url(self):
        return reverse('mp3:album_detail', kwargs={'slug': self.get_object().slug})


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_name', 'genre', 'price', 'album_logo']

    def form_valid(self, form):
        form.instance.uploaded_by = self.request.user
        form.save()
        return super(AlbumCreate, self).form_valid(form)


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_name', 'genre', 'price', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('mp3:album_list')


class SongList(ListView):
    model = Song
    context_object_name = 'songs'
    template_name = 'mp3/song_list.html'
    paginate_by = 20

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.album = get_object_or_404(Album, slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super(SongList, self).get_context_data(**kwargs)
        context['album'] = self.album
        return context

    def get_queryset(self):
        return self.album.song_set.order_by('-song_title')


class SongCreate(CreateView):
    model = Song

    def get(self, request, *args, **kwargs):
        form = SongForm
        print(self.kwargs)
        return render(request, 'mp3/song_form.html', {'form': form})

    def post(self, request, *args, **kwargs):
        # -------get album instance------
        album_obj = Album.objects.get(slug=self.kwargs.get('slug'))
        if request.method != 'POST':
            form = SongForm()
            return render(request, 'mp3/song_form.html', {'form': form})
        form = SongForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('mp3:album_detail', slug=album_obj.slug)


class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('mp3:song_list')

mp3/templates/mp3/album_confirm_delete.html
{% extends 'layout.html' %}
{% load humanize %}

{% block title %}Album confirm delete{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="wrapper">
        <div class="container">
            <div class="content-center">
                <div class="row">
                    <div class="info">
                        <div class="icon icon-primary">
                            <i class="fa fa-recycle"></i>
                        </div>
                        <br>
                        <br>
                        <div class="description">
                            <h5>Delete {{ album.album_title }}</h5>
                            <p>Dear {{ request.user }} do you wish to delete this album?...</p>
                            <br>
                            <br>
                            <form method='POST'>
                                {% csrf_token %}
                                <input type='submit' class="btn btn-danger" value='delete'>
                                <a href="{% url 'mp3:album_list' %}">Cancel</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

mp3/templates/mp3/album_detail.html
{% extends 'layout.html' %}
{% block title %}Albums{% endblock %}

{% block content %}
<body class="blog-posts sidebar-collapse">

  <div class="wrapper">
    <div class="main">
      <div class="section section-dark text-white">
        <div class="container">
          <div class="row">
            <div class="col-md-10 ml-auto mr-auto text-center title">

              <div class="info">
                <div class="icon icon-primary">
                    <i class="fa fa-archive"></i>
                </div>
                <div class="description">
                    <h4 class="info-title">Here are available songs for {{ album.album_name }}</h4>
                    <p>This album was written and composed by {{ album.artist }}<br>
                        We hope you'll find the {{ album.album_songs }} track{{ album.album_songs|pluralize }} already published really enjoyable.</p>
                </div>
                <br>
                <br>
                <div class="description">
                    {% if request.user.is_authenticated  %}
                        {% if album.album_songs and request.user not in album.owned_by.all %}
                            <form>
                              <script src="https://js.paystack.co/v1/inline.js"></script>
                                <button class="btn btn-info btn-sm btn-icon" type="button" onclick="payWithPaystack()">click here and Buy the full album ₦{{ album.price }}</button>
                            </form>
                        {% elif not album.album_songs %}
                            <p>This album currently has no songs.</p>
                            <p>Do check later for more updates on this album.</p>
                        {% else %}
                            <p>Dear <strong>{{ request.user.username }}</strong> you can play and download all the songs for this album.</p>
                            <p>We thank you for your patronization and support.</p>
                        {% endif %}
                    {% else %}
                        <a class="btn btn-primary btn-sm btn-icon" type="button" href="{% url 'accounts:login' %}">Please login to access and buy this album.</a>
                    {% endif %}
                    <!-- place below the html form -->
                    <script>
                      function payWithPaystack(){
                          {% include 'includes/ajax_csrf_token.js' %}
                          var handler = PaystackPop.setup({
                          key: '{{ key }}',
                          email: '{{ request.user.email|safe }}',
                          amount: {{ album.price|safe }} * 100,
                          ref: 'nwbn'+Math.floor((Math.random() * 100000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
                          metadata: {
                             custom_fields: [
                                {
                                    display_name: "{{ request.user.username|safe }}",
                                    variable_name: "{{ request.user.email|safe }}",
                                    value: "{{ request.user.phone|safe }}"
                                }
                             ]
                          },
                          callback: function(response){
                            console.log(response);
                            swal("Payment complete!", "Reference: " + response.reference, response.status);
                            if (response.status === "success") {
                                $.ajax({
                                    url: "{% url 'mp3:album_detail' slug=album.slug %}",
                                    method: 'post',
                                    data: {'referenceId': response.reference, 'paid_user': '{{ request.user }}', 'album_name': '{{ album.album_name }}'},
                                    contentType: "application/x-www-form-urlencoded",
                                    success: function (data) {
                                        console.log(data);
                                        setTimeout(function () {
                                            window.location.replace("{% url 'mp3:album_detail' slug=album.slug %}");
                                        });
                                    }
                                });

                            }
                            else  {
                                swal("Transaction was not completed", "window closed.", response.status);
                            }
                          },
                          onClose: function(){
                              swal("window closed.");
                          }
                        });
                        handler.openIframe();
                      }
                    </script>
                    <!--// place below the html form -->
                </div>
              </div>
            </div>
          </div>

        {% if album.album_songs %}
            <nav aria-label="breadcrumb" role="navigation">
              <ol class="breadcrumb">
                <li class="breadcrumb-item" aria-current="page"><strong><a href="{% url 'mp3:album_list' %}">Albums</a></strong></li>
                <li class="breadcrumb-item active" aria-current="page">Songs</li>
              </ol>
            </nav>
        {% endif %}

          <table class="table text-white">
            <thead>
                <tr>
                    <th class="text-center">Song title</th>
                    <th class="text-center">Play</th>
                    <th class="text-center">Download</th>
{#                    <th class="text-center">Actions</th>#}
                </tr>
            </thead>
            <tbody>
            {% for song in songs %}
                <tr>
                    <td class="text-center">{{ song.song_title }}</td>

                    {% if request.user.is_superuser %}
                        <td class="text-center">
                            <audio controls="controls" controls="download"> <br>
                              <source src="{{ song.audio_file.url }}" type="audio/mp3" />
                            </audio>
                        </td>
                        <td class="td-actions text-center">
                            <a class="btn btn-info btn-sm btn-icon" href="{{ song.audio_file.url }}" type="submit" target="_blank" download>
                                <i class="fa fa-download"></i>
                            </a>
                            <button type="button" rel="tooltip" class="btn btn-danger btn-sm btn-icon">
                                <i class="fa fa-times"></i>
                            </button>
                        </td>
                    {% elif request.user.is_authenticated and request.user in album.owned_by.all %}
                        <td class="text-center">
                            <audio controls="controls" controls="download"> <br>
                              <source src="{{ song.audio_file.url }}" type="audio/mp3"/>
                            </audio>
                        </td>
                        <td class="td-actions text-center">
                            <a class="btn btn-info btn-sm btn-icon" href="{{ song.audio_file.url }}" type="submit" target="_blank" download>
                                <i class="fa fa-download"></i>
                            </a>
                        </td>
                    {% elif request.user.is_authenticated %}
                        <td class="text-center">
                            <button
                                class="btn btn-primary btn-sm"
                                ngbPopover="Thank you for patronizing with us click on the link above to buy the full album"
                                popoverTitle="Buy the album to play"
                                title="Buy the album to play"
                                type="button">play</button>
                        </td>
                        <td class="td-actions text-center">
                            <a class="btn btn-info btn-sm btn-icon disabled" href="#">
                                <i class="fa fa-download"></i>
                            </a>
                        </td>
                    {% else %}
                        <td class="text-center">
                            <a type="button"
                                class="btn btn-primary btn-sm"
                                href="{% url 'accounts:login' %}"
                                ngbTooltip="login to buy this album and play"
                                placement="top"
                                type="button">play</a>
                        </td>
                        <td class="td-actions text-center">
                            <a class="btn btn-info btn-sm btn-icon disabled" href="#">
                                <i class="fa fa-download"></i>
                            </a>
                        </td>
                    {% endif %}
                </tr>
            {% empty %}
                <div class="info">
                    <div class="description">
                        <h4 class="info-title">No Song list yet for this album</h4>
                        <p>No Song list yet for this album please check back often as we make the songs available stay tuned.</p>
                    </div>
                </div>
            {% endfor %}
            </tbody>
          </table>
            <hr>
            <br>
            <br>
            {% if user.is_superuser %}
                <a class="btn btn-primary btn-round btn-sm" href="{% url 'mp3:add_song' object.slug %}">Add songs here</a>
            {% endif %}
            <br>
            <br>
            <br>
            <br>
        </div>
      </div>
    </div>
  </div>

</body>
{% endblock %}

mp3/templates/mp3/album_form.html
{% extends "layout.html" %}
{% block title %}Create an Album{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <div class="col-md-6 ml-auto mr-auto text-center">
        <h4 class="info-title text-center"> Add an Album </h4>
        <p class="text-center">Add a new album now </p>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button class="btn btn-rotate btn-round" type="submit"><i class="fa fa-upload"></i>add album</button>
        </form>
    </div>
    <br>
    <br>
{% endblock %}

mp3/templates/mp3/album_list.html
{% extends 'layout.html' %}
{% block title %}Albums{% endblock %}

{% block content %}
    <body class="product-page sidebar-collapse">

        <div class="page-header page-header-xs" style="background-image: url('https://res.cloudinary.com/geetechlab-com/image/upload/v1612913403/nwaben.com/music-3888684_1280_gtqxnv.png');">
            <div class="filter"></div>
        </div>

        <div class="main">
            <div class="section">
              <div class="container align-content-center">
                <div class="row">
                  <div class="col-md-12">
                        <div class="description">
                            <h4 class="info-title">FURTHER DETAILS ON THE MUSIC</h4>
                            <br>
                            <p style="color: black">The music is basically meant to entertain you. You'll find that
                                they are indeed all sweet music with
                                lyrics that we try to keep generally positive and constructive.</p>
                            <br>
                            <p style="color: black">We are beginning with music that could be termed 'western' with
                                lyrics in English. Seven tracks of this kind are already
                                published in this music section of this website, some more of
                                this kind will follow with time. Later we hope to diversify into other
                                kinds of music and in some other languages. Time shall tell.</p>
                            <br>
                            <br>
                        </div>
                    <nav aria-label="breadcrumb" role="navigation">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Albums</li>
                      </ol>
                    </nav>
                  </div>
                  <div class="col-md-12">
                    <div class="table-responsive">
                      <table class="table table-shopping">
                          <thead>
                              <tr>
                                  <th class="text-center"></th>
                                  <th class="text-center">Album name</th>
                                  <th class="text-center">No of tracks</th>
                                  <th class="text-center">Genre</th>
                                  <th class="text-center">Artist</th>
                                  <th></th>
                              </tr>
                          </thead>
                          <tbody>
                          {% for album in albums %}
                              <tr>
                                  <td class="text-center">
                                      <div class="img-container">
                                          <img src="{{ album.image_url }}" alt="{{ album.album_name }}">
                                      </div>
                                  </td>
                                  <td class="td-name text-center">
                                      <a href="{% url 'mp3:album_detail' slug=album.slug %}">{{ album.album_name }}</a>
                                      <br><small>added by {{ album.uploaded_by }}</small>
                                  </td>
                                  <td class="text-center">
                                      {{ album.album_songs }}
                                  </td>
                                  <td class="text-center">
                                      {{ album.genre }}
                                  </td>
                                  <td class="text-center">
                                      {{ album.artist }}
                                  </td>

                                  {% if user.is_superuser  %}
                                      <td class="td-actions">
                                          <a class="btn btn-info btn-sm" type="submit" href="{% url 'mp3:delete_album' album.slug %}">
                                            <i class="fa fa-trash"></i> delete
                                          </a>
                                      </td>
                                  {% endif %}
                              </tr>
                          {% empty %}
                            <div class="info">
                                <div class="icon icon-primary">
                                    <i class="fa fa-music"></i>
                                </div>
                                <div class="description">
                                    <h4 class="info-title"> No Available Album Yet </h4>
                                </div>
                            </div>
                          {% endfor %}
                          </tbody>
                      </table>
                    </div>
                  {% if request.user.is_superuser %}
                    <div class="info">
                        <div class="description">
                            <p>
                            <a class="btn btn-primary btn-link" href="{% url 'mp3:add_album' %}">click here</a> to add albums</p>
                            </p>
                        </div>
                    </div>
                  {% endif %}
                  </div>
                </div>
              </div>
            </div>
        </div>




    <script>
        let price = document.getElementById("{{ album.price }}");

      function makePayment() {
        FlutterwaveCheckout({
          public_key: {{ key|safe }},
          tx_ref: "hooli-tx-1920bbtyt",
          amount: price,
          currency: "NGN",
          payment_options: "card,mobilemoney,ussd",
          customer: {
            email: "{{ request.user.email|safe }}",
            phonenumber: "{{ request.user.phone|safe }}",
            name: "{{ request.user.username|safe }}",
          },
          callback: function (data) { // specified callback function
            console.log(data);
          },
          customizations: {
            title: "Nwaben Store",
            description: "Payment for the Music album",
            logo: "https://assets.piedpiper.com/logo.png",
          },
        });
      }
    </script>


    </body>
{% endblock %}

mp3/templates/mp3/song_form.html
{% extends "layout.html" %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

{% block title %}{{ song.album.album_name }}{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="col-md-5 ml-auto mr-auto text-center" id="direct_upload">
        <h4 class="info-title text-center"> Add a song </h4>
        <p class="text-center">Add a new Song Track for {{ song.album.album_title }} </p>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "includes/form.html" %}
            <button class="btn btn-rotate btn-round" type="submit"><i class="fa fa-upload"></i>add song</button>
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

mp3/templates/mp3/song_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>