accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('profile/update', views.UserProfileView.as_view(), name='profile_update'),
]

articles/urls.py
from django.urls import path
from articles import views

urlpatterns = [
    path('category/create', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>', views.ArticleCategory.as_view(), name='article_category'),
    path('delete/<slug:slug>', views.ArticleDelete.as_view(), name='article_delete'),
    path('update/<slug:slug>', views.ArticleUpdate.as_view(), name='article_update'),
    path('dashboard/', views.DashBoard.as_view(), name='article_dashboard'),
    path('create/', views.ArticleCreate.as_view(), name='article_create'),
    path('details/<slug:slug>', views.ArticleDetail.as_view(), name='article_detail'),
    path('', views.ArticleList.as_view(), name='article_list'),
]

mp3/urls.py
from django.urls import path
from . import views


app_name = 'mp3'

urlpatterns = [
    path('', views.AlbumList.as_view(), name='album_list'),
    path('<slug:slug>/', views.AlbumDetail.as_view(), name='album_detail'),
    path('album/add/', views.AlbumCreate.as_view(), name='add_album'),
    path('album/<slug:slug>/', views.AlbumUpdate.as_view(), name='update_album'),
    path('album/<slug:slug>/delete', views.AlbumDelete.as_view(), name='delete_album'),
    path('songs/', views.SongList.as_view(), name='song_list'),
    path('song/<slug:slug>/add/', views.SongCreate.as_view(), name='add_song'),
    path('song/<slug:slug>/delete', views.SongDelete.as_view(), name='delete_song'),
]

nwaben/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic import TemplateView
from nwaben.views import ContactView

urlpatterns = [
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('burial_memories/', include('burial_memories.urls', namespace='burial_memories')),
    path('about/', ContactView.as_view(), name='about'),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),
    # path('archives/', include('archive.urls', namespace='archives')),
    path('mp3/', include('mp3.urls', namespace='mp3')),
    path('search/', include('search.urls', namespace='search')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('summernote/', include('django_summernote.urls')),
]

# urlpatterns += staticfiles_urlpatterns()
# # Remove this conditional check if you want to upload to Heroku
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# administrator backend service url
urlpatterns += [
    path('admin-family-nwaben/', admin.site.urls),
]

# Url to catch any un-matched pattern and render 404
urlpatterns += [re_path(r'^.*.', TemplateView.as_view(template_name='404.html'), name='404_')]

articles/models.py
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from nwaben.storage_backends import PublicMediaStorage


def upload_dir(instance, filename):
    return "{}/{}".format(instance.author, filename)


class ArticleQuerySet(models.query.QuerySet):
    def not_draft(self):
        return self.filter(draft=False)


class ArticleManager(models.Manager):
    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().not_draft()


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("articles_by_category", args=[self.name])


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    image = models.ImageField(storage=PublicMediaStorage(), upload_to=upload_dir, blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, null=False)
    view_count = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(default=timezone.now)
    draft = models.BooleanField(default=True)
    description = RichTextField(blank=True, null=True, config_name='special')
    body = RichTextUploadingField(blank=True, null=True,
                                  external_plugin_resources=[('youtube', '/static/youtube/', 'plugin.js')])
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    objects = ArticleManager()

    class Meta:
        verbose_name_plural = "Articles"
        ordering = ('-created',)
        unique_together = ["slug", "title", ]

    def __str__(self):
        return self.title

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return 'https://res.cloudinary.com/geetechlab-com/image/upload/v1580824596/nwaben.com/blog_image1_eklmqy.jpg'

    def get_absolute_url(self):
        return reverse("articles:article_detail", kwargs={"slug": self.slug})


def article_pre_save_signal(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)
        new_slug = "{}-{}".format(instance.title, instance.id)
        try:
            instance.slug = slugify(new_slug)
        except Article.DoesNotExist:
            instance.slug = instance.slug
        except Article.MultipleObjectsReturned:
            instance.slug = slugify(new_slug)
        except:
            pass


pre_save.connect(article_pre_save_signal, sender=Article)


class Comment(models.Model):
    article = models.ForeignKey(Article, related_name="comments", on_delete=models.CASCADE)
    by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # content = RichTextUploadingField(blank=True, null=True, config_name='comment_content')
    content = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approved(self):
        self.approved = True
        self.save()

    def __str__(self):
        return '{} - {}'.format(self.content, self.by)

    class Meta:
        ordering = ['created_on']


class Reply(models.Model):
    comment = models.ForeignKey(Comment, related_name='replies', on_delete=models.CASCADE)
    replied_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    replied_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['replied_on']

articles/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField

from articles.models import Article, Comment, Category, Reply


class ArticleForm(forms.ModelForm):
    category = forms.CharField(label='Category')

    class Meta:
        model = Article
        fields = ("category",
                  "title",
                  "description",
                  "image",
                  "body",
                  "draft",)
        # widgets = {
        #     'description': SummernoteWidget(),
        #     'body': SummernoteWidget(),
        # }


class CategoryForm(forms.ModelForm):
    name = forms.CharField()

    class Meta:
        model = Category
        fields = ("name",)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': SummernoteWidget(),
        }


class ReplyForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'reply this comment', 'rows': '3'}), label="",)

    class Meta:
        model = Reply
        fields = ("content",)

articles/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views import View
from .forms import ArticleForm, CommentForm, CategoryForm, ReplyForm
from .models import Category, Article, Comment, Reply


class ArticleList(generic.CreateView, generic.ListView):
    fields = ("category", "title", "description", "image", "body", "draft")
    model = Article
    context_object_name = 'articles'
    paginate_by = 4
    template_name = "articles/article_list.html"


class DashBoard(View):
    def get(self, request, *args, **kwargs):
        view = ArticleList.as_view(template_name="articles/admin_page.html")
        return view(request, *args, **kwargs)


class ArticleDisplay(generic.DetailView, generic.UpdateView):
    fields = ("category", "title", "description", "image", "body", "draft")
    model = Article
    context_object_name = 'article'
    template_name = 'articles/article_detail.html'

    def get_object(self):
        view_count_obj = super(ArticleDisplay, self).get_object()
        view_count_obj.view_count += 1
        view_count_obj.save()
        return view_count_obj

    def get_context_data(self, **kwargs):
        context = super(ArticleDisplay, self).get_context_data(**kwargs)
        # comment_obj = Comment.objects.get(article=self.get_object())
        comments = Comment.objects.filter(article=self.get_object())
        context['comments'] = comments
        # context['replies'] = Reply.objects.filter(comment=comment_obj)
        context['form'] = CommentForm
        # context['reply_form'] = ReplyForm
        return context


class ArticleComment(LoginRequiredMixin, generic.FormView):
    form_class = CommentForm
    template_name = 'articles/article_detail.html'

    def form_valid(self, form):
        form.instance.by = self.request.user
        article = Article.objects.get(slug=self.kwargs['slug'])
        form.instance.article = article
        form.save()
        return super(ArticleComment, self).form_valid(form)

    def get_success_url(self):
        return reverse('articles:article_detail', kwargs={'slug': self.kwargs['slug']})


# class CommentReply(LoginRequiredMixin, generic.FormView):
#     form_class = ReplyForm
#     template_name = 'articles/comment_reply.html'
#
#     def form_valid(self, form):
#         form.instance.replied_by = self.request.user
#         comment = Comment.objects.get(pk=self.kwargs['pk'])
#         form.instance.comment = comment
#         form.save()
#         return super(CommentReply, self).form_valid(form)
#
#     def get_success_url(self):
#         return reverse('articles:article_detail', kwargs={'slug': self.kwargs['slug']})
#
#
#
# class CommentDisplay(generic.DetailView):
#     model = Comment
#     template_name = "articles/comment_reply.html"
#
#     def get_context_data(self, **kwargs):
#         context = super(CommentDisplay, self).get_context_data(**kwargs)
#         replies = Reply.objects.filter(comment=self.get_object())
#         context['replies'] = replies
#         context['form'] = ReplyForm
#         print(replies)
#         return context


# class CommentDetail(View):
#     def get(self, request, *args, **kwargs):
#         view = CommentDisplay.as_view()
#         return view(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         view = CommentReply.as_view()
#         return view(request, *args, **kwargs)


class ArticleDetail(View):
    def get(self, request, *args, **kwargs):
        view = ArticleDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ArticleComment.as_view()
        return view(request, *args, **kwargs)


class ArticleCreate(LoginRequiredMixin, generic.CreateView):
    model = Article
    fields = ("category", "title", "description", "image", "body", "draft")

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return super(ArticleCreate, self).form_valid(form)


class ArticleUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Article
    fields = ("category", "title", "description", "image", "body", "draft")

    # Here we print out the name of the page updated
    def get_page_title(self):
        obj = self.get_object()
        return "Update {}".format(obj.name)


class ArticleDelete(LoginRequiredMixin, generic.DeleteView):
    model = Article
    success_url = reverse_lazy("articles:article_dashboard")

    # Here we overide the delete function to only work if a user is a superuser
    def get_queryset(self):
        if not self.request.user.is_superuser:
            return self.model.objects.filter(author=self.request.user)
        return self.model.objects.all()


class ArticleCategory(generic.ListView):
    model = Article
    template_name = "articles/article_category.html"

    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return Article.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super(ArticleCategory, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context


class CategoryCreate(generic.CreateView):
    model = Category
    template_name = 'articles/category_form.html'
    fields = ('name',)

    def form_valid(self, form):
        form.instance = self.request.user
        form.save()
        return super(CategoryCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('articles:article_create')

articles/templates/articles/admin_page.html
{% extends 'layout.html' %}
{% load humanize %}

{% block title %}Article Dashboard{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <div class="wrapper">
        <div class="container">
            <div class="content-center">
                <div class="row">
                    <div class="info">
                        <div class="icon icon-primary">
                            <img class="img-thumbnail img-responsive" src="{{ request.user.image_url }}">
                        </div>
                        <div class="description">
                            <h4 class="info-title"> Welcome {{ request.user }} </h4>
                            <p>You were able to view this page due to your admin/super_user privilages...</p>
                            <hr>
                            <p>Click <a class="btn btn-primary btn-round" href="{% url 'articles:article_create' %}">
                                <i class="fa fa-plus"></i> here </a> to add more articles
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Author</th>
                                <th class="text-right">Date created</th>
                                <th class="text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for article in articles %}
                            <tr>
                                <td>{{ article.title }}</td>
                                <td>{{article.description|safe|truncatewords:10}}</td>
                                <td>{{ article.author.username }}</td>
                                <td class="text-right">{{ article.created|naturaltime }}</td>
                                <td class="td-actions text-right">
                                    <button type="button" rel="tooltip" class="btn btn-success btn-sm btn-icon">
                                        <a href="{% url 'articles:article_update' article.slug %}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </button>
                                    <button type="button" rel="tooltip" class="btn btn-danger btn-sm btn-icon">
                                        <a href="{% url 'articles:article_delete' article.slug %}">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </button>
                                </td>
                            </tr>
                            {% empty %}

                                <div class="info">
                                    <div class="icon icon-primary">
                                        <i class="fa fa-archive"></i>
                                    </div>
                                    <div class="description">
                                        <h4 class="info-title"> Add article </h4>
                                        <p>Click
                                            <a class="btn btn-primary btn-round" href="{% url 'articles:article_create' %}">
                                                <i class="fa fa-plus"></i> here
                                            </a>
                                             to add articles
                                        </p>
                                    </div>
                                </div>

                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            <hr>
            {% include 'includes/pagination.html' %}
            </div>
        </div>
    </div>
{% endblock %}

articles/templates/articles/article_category.html
{% extends 'layout.html' %}
{% block title %}Articles{% endblock %}

{% block content %}
    
{% endblock %}

articles/templates/articles/article_confirm_delete.html
{% extends 'layout.html' %}
{% load humanize %}

{% block title %}Article Dashboard{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="wrapper">
        <div class="container">
            <div class="content-center">
                <div class="row">
                    <div class="info">
                        <div class="icon icon-primary">
                            <i class="fa fa-recycle"></i>
                        </div>
                        <br>
                        <br>
                        <div class="description">
                            <h5>Delete {{ article.title }}</h5>
                            <p>Dear {{ request.user }} do you wish to delete this article?...</p>
                            <br>
                            <br>
                            <form method='POST'>
                                {% csrf_token %}
                                <input type='submit' class="btn btn-danger" value='delete'>
                                <a href="{% url 'articles:article_dashboard' %}">Cancel</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'layout.html' %}
{% load humanize %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %}Articles{% endblock %}

{% block content %}


<div class="blog-post sidebar-collapse">

  <div class="page-header page-header-small" data-parallax="true" style="background-image: url('{{ article.image_url }}')">
    <div class="filter"></div>
    <div class="content-center">
      <div class="motto">
        <h1 class="title-uppercase text-center">{{ article.title }}</h1>
        <h3 class="text-center">{{ article.details|safe|truncatewords:10 }}</h3>
          <p>Scroll below to read the rest of the contents...</p>
        <br/>
        <button id="share_article" class="btn btn-warning btn-round btn-lg">
          <i class="fa fa-share-alt" aria-hidden="true"></i> Share Article
        </button>
          <script>
            let text_to_copy = document.URL;
            let copy_button = document.getElementById("share_article");

            copy_button.addEventListener("click", function(){
                let temp = document.createElement("INPUT");
                temp.value = text_to_copy;
                document.body.appendChild(temp);
                temp.select();
                document.execCommand("copy");
                temp.remove();
                swal("Link Copied!", "You can go ahead and share this article...");
            });
          </script>
      </div>
    </div>
  </div>
  <div class="wrapper">
    <div class="main">
      <div class="section section-white">
        <div class="container">
          <div class="row">
            <div class="col-md-6 ml-auto mr-auto text-center title">
              <h2>{{ article.title }}</h2>
              <h3 class="title-uppercase">
                <small>{{ article.author }}</small>
              </h3>
            </div>
          </div>
          <div class="row">
            <div class="col-md-10 ml-auto mr-auto">
              <div class="text-center">
                <span class="badge badge-warning main-tag">{{ article.category }}</span>
                  <h3 class="title">{{ article.description|safe|linebreaks}}</h3>
                <h6 class="title-uppercase">{{ article.created|naturaltime }}</h6>
              </div>
            </div>
            <div class="col-md-10 ml-auto mr-auto">
                <div class="card" data-radius="none" style="background-image: url('{{ article.image_url }}');"></div>
                <br>
                <br>
              <div class="article-content">
                <p>
                    {{ article.body|safe|linebreaks }}
                </p>
              </div>
          <hr>
            <div class="row">
              <div class="container">
                  <div class="media">
                    <a class="pull-left" href="#">
                      <div class="avatar big-avatar">
                        <img class="media-object" alt="{{ article.author }}" src="{{ article.author.image_url }}">
                      </div>
                    </a>
                    <div class="media-body">
                      <p class="media-heading">by: <strong>{{ article.author }}</strong></p>

                      <p class="media-footer" >{{ article.author.bio }}</p>
                    </div>
                  </div>
              </div>
            </div>


        </div>
          </div>
        </div>
      </div>

      <div class="section section-nude-gray">
        <div class="container container-tim">
          <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
              <div class="media-area">
                <h3>Comment{{ comments.count|pluralize }} · {{ comments.count }}</h3>
                <!--  Comment                    -->
                {% for comment in comments %}
                <div class="media">
                  <a class="pull-left" href="#paper-kit">
                    <div class="avatar">
                      <img class="media-object" alt="Tim Picture" src="{{ comment.by.image_url }}">
                    </div>
                  </a>
                  <div class="media-body">
                    <h5 class="media-heading">{{ comment.by.username }}</h5>
                    <div class="pull-right">
                      <h6 class="text-muted">{{ comment.created_on|naturaltime }}</h6>
                    </div>
                    <p>{{ comment.content|safe }}</p>
                    <!--
                    <div class="media-footer">
                      <a href="#" class="btn btn-danger btn-link">
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i> 0
                      </a>
                      <a href="#" class="btn btn-link">
                        <i class="fa fa-thumbs-down" aria-hidden="true"></i> 0
                      </a>
                      <a href="#" class="btn btn-link">
                        Follow · 0
                      </a>
                    </div>
                    -->
                    <!--__Reply include tag goes here__-->

                  </div>
                </div>
                {% empty %}
                    <div class="media-body">
                        <p>No comment yet, be the first to comment this article...</p>
                    </div>
                <!-- end media -->
                {% endfor %}
              </div>

              <!-- end media-area -->
            <hr>
            </div>
            <!-- end col-md-8 -->
          </div>
          <!-- end row -->
        </div>
      </div>

    {% if user.is_authenticated %}
      <div class="section section-gray">
        <div class="container tim-container">
          <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
              <h3 class="text-center">Post your comment</h3>
              <div class="media media-post">
                <a class="pull-left author">
                  <div class="avatar">
                    <img class="media-object" alt="64x64" src="{{ user.image_url }}">
                  </div>
                </a>
                <form class="form media-body" method="POST">
                    {% csrf_token %}
                    {{ form.media }}
                    {% render_field form.content class="form-control" placeholder="write your comments here...", rows="4" %}
                  <div class="media-footer">
                    <button type="submit" class="btn btn-info btn-wd pull-right">Post Comment</button>
                  </div>
                </form>
              </div>
              <!-- end media-post -->
            {% else %}
                <h5 class="text-center">you need to <a href="{% url 'accounts:login' %}">login</a> to be able to comment this article</h5>
            </div>
          </div>
          <!-- end row -->
        </div>
      </div>
        <hr>
    {% endif %}

        <!--
          <div class="row">
            <div class="related-articles">
              <h3 class="title">Related articles</h3>
              <legend></legend>
              <div class="container">
                <div class="row">
                  <div class="col-md-4">
                    <a href="pkp">
                      <img src="../assets/img/sections/damir-bosnjak.jpg" alt="Rounded Image" class="img-rounded img-responsive">
                    </a>
                    <p class="blog-title">My Review of Pitchfork’s ‘Indie 500’ Album Review</p>
                  </div>
                  <div class="col-md-4">
                    <a href="pkp">
                      <img src="../assets/img/sections/por7o.jpg" alt="Rounded Image" class="img-rounded img-responsive">
                    </a>
                    <p class="blog-title">Top Events This Month</p>
                  </div>
                  <div class="col-md-4">
                    <a href="pkp">
                      <img src="../assets/img/sections/jeff-sheldon.jpg" alt="Rounded Image" class="img-rounded img-responsive">
                    </a>
                    <p class="blog-title">You Should Get Excited About Virtual Reality. Here’s Why.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          -->
    </div>
  </div>
        <!--<br>
            <div class="pagination-area">
              <ul class="pagination pagination-primary pagination-no-border justify-content-center">
                <li class="page-item">
                  <a href="#paper-kit" class="page-link"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a>
                </li>
                <li class="page-item active">
                  <a href="#paper-kit" class="page-link">1</a>
                </li>
                <li class="page-item">
                  <a href="#paper-kit" class="page-link">2</a>
                </li>

                <li class="page-item">
                  <a href="#paper-kit" class="page-link"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                </li>
              </ul>
            </div>
          </div>
          -->

</div>

{% endblock %}

articles/templates/articles/article_form.html
{% extends "layout.html" %}
{% load widget_tweaks %}

{% block title %}Create an Article{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <div class="col-md-6 ml-auto mr-auto text-center">
        <h4 class="info-title text-center"> Create an Article </h4>
        <p class="text-center">Start a new article now or <a href="{% url 'articles:category_create' %}">click here</a> to add a new category</p>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            <div class="form-group">
                <label for="category" >category</label>
                {% render_field form.category id="category" class="form-control" placeholder="select category"  %}
            </div>
            <br>
            <label>title</label>
            {% render_field form.title class="form-control" placeholder="title" %}
            <br>
            <label>category</label>
            {% render_field form.description class="form-control" placeholder="write a short description here", rows="4" %}
            <br>
            <label>choose a cover image</label>
            {% render_field form.image class="form-control" placeholder="upload image" %}
            <br>
            <label>body of the article</label>
            {% render_field form.body class="form-control" placeholder="Write the body of the article here", rows="4" %}
            <br>
            <label class="form-check-label">
            {% render_field form.draft class="form-control" %}
                Uncheck here to publish or leave it as draft by default.
                <span class="form-check-sign"></span>
            </label>
            <br>
            <br>

            <button class="btn btn-rotate btn-round" type="submit"><i class="fa fa-paper-plane"></i>publish article</button>
        </form>
    </div>
    <br>
{% endblock %}