burial_memories/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'burial_memories'

urlpatterns = [
    path("", views.BurialMemoryList.as_view(), name='list'),
    path('create/', views.BurialMemoryCreate.as_view(), name='create'),
    path("<slug:slug>/", views.BurialMemoryDetail.as_view(), name='detail'),
    path('update/<slug:slug>', views.BurialMemoryUpdate.as_view(), name='update'),
    path('delete/<slug:slug>', views.BurialMemoryDelete.as_view(), name='delete'),
]

htmx_urlpatterns = [
    path('<slug:slug>/tribute/', views.add_tribute, name='add_tribute'),
    path('<slug:slug>/donate/', csrf_exempt(views.add_donation), name='add_donation'),
    path('<slug:slug>/donation_list/', views.list_donations, name='list_donations'),
    path('gallery_list/<slug:slug>/', views.list_gallery, name='list_gallery'),
]

urlpatterns += htmx_urlpatterns

mp3/urls.py
from django.urls import path
from . import views


app_name = 'mp3'

urlpatterns = [
    path('', views.AlbumList.as_view(), name='album_list'),
    path('<slug:slug>/', views.AlbumDetail.as_view(), name='album_detail'),
    path('album/add/', views.AlbumCreate.as_view(), name='add_album'),
    path('album/<slug:slug>/', views.AlbumUpdate.as_view(), name='update_album'),
    path('album/<slug:slug>/delete', views.AlbumDelete.as_view(), name='delete_album'),
    path('songs/', views.SongList.as_view(), name='song_list'),
    path('song/<slug:slug>/add/', views.SongCreate.as_view(), name='add_song'),
    path('song/<slug:slug>/delete', views.SongDelete.as_view(), name='delete_song'),
]

templates/404_.html
{% extends 'layout.html' %}
{% block title %}404{% endblock %}
{% block content %}
    <!--     *********     HEADER 2      *********      -->
    <div class="header-2">
      <div class="page-header" style="background-image: url('#');">
        <div class="filter"></div>
        <div class="content-center">
          <div class="container">
            <div class="row">
              <div class="col-md-8 ml-auto mr-auto text-center">
                <h1 class="title">Page 404</h1>
                <h5 class="description">seems you visited the wrong page <br>
                </h5>
                <br />
              </div>
              <div class="col-md-10 ml-auto mr-auto">
                <h5><a href="{% url 'home' %}">click here</a> to get back to home page</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--     *********    END HEADER 2      *********      -->
{% endblock %}

templates/about.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block title %}about{% endblock %}

{% block content %}
<!-- SweetAlert -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>



<div class="about-us sidebar-collapse">
  <!-- Extra details for Live View on GitHub Pages -->

  <div class="page-header page-header-small" style="background-image: url('https://res.cloudinary.com/geetechlab-com/image/upload/v1612913403/nwaben.com/musicians-690591_1280_oculpq.jpg')">
    <div class="filter filter-danger"></div>
    <div class="content-center">
      <div class="container">
        <h3>MISSION STATEMENT OF THE NWAZURUOKE NWABEN FAMILY</h3>
          <br>
        <h5 style="color: white">To make this world a more beautiful place through music and order</h5>
          <h5>We are using this website to showcase our music to the whole world.</h5>
      </div>
    </div>
  </div>
  <div class="wrapper">
    <div class="section text-center landing-section">
      <div class="container">
        <div class="row">
          <div class="col-md-10 ml-auto mr-auto">
            <h3 class="title"> More Features from us: </h3>
            <h5 style="color: black">There is also the blogging section of this website where we publish some write ups that are meant for the positive
            development/improvement of the individual and the world in general.</h5>
          </div>
        </div>
        <br />
        <br />
        <div class="row">
          <div class="col-md-3">
            <div class="info">
              <div class="icon icon-danger">
                <i class="fa fa-file-audio-o"></i>
              </div>
              <div class="description">
                <h4 class="info-title">Audio Files</h4>
                <p class="description">View our album to start playing...</p>
                <a href="{% url 'mp3:album_list' %}" class="btn btn-link btn-danger">See more</a>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info">
              <div class="icon icon-danger">
                <i class="fa fa-podcast"></i>
              </div>
              <div class="description">
                <h4 class="info-title">Podcast</h4>
                <p>Play our album on podcast...</p>
                <a href="#" class="btn btn-link btn-danger">See more</a>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info">
              <div class="icon icon-danger">
                <i class="fa fa-soundcloud"></i>
              </div>
              <div class="description">
                <h4 class="info-title">Sound Cloud</h4>
                <p>Download our album on sound cloud...</p>
                <a href="#" class="btn btn-link btn-danger">See more</a>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info">
              <div class="icon icon-danger">
                <i class="fa fa-headphones"></i>
              </div>
              <div class="description">
                <h4 class="info-title">Play our Songs now.</h4>
                <p>Click to play our song at the go...</p>
                <a href="{% url 'mp3:album_list' %}" class="btn btn-link btn-danger">click to play <i class="fa fa-play-circle"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="section section-dark text-center landing-section">
      <div class="container">
        <h2 class="title">Our Team</h2>
        <div class="row">
            {% for user in staff_users %}
              <div class="col-md-4">
                <div class="card card-profile card-plain">
                  <div class="card-avatar">
                    <a href="#">
                      <img src="{{ user.image_url }}" alt="{{ user.username }}">
                    </a>
                  </div>
                  <div class="card-body">
                    <a href="#">
                      <div class="author">
                        <h4 class="card-title">{{ user.username }}</h4>
                        <h6 class="card-category text-muted">Staff Member</h6>
                      </div>
                    </a>
                      {% if user.bio %}
                        <p class="card-description text-center">
                          {{ user.bio|linebreaks }}
                        </p>
                      {% endif %}
                  </div>
                  <div class="card-footer text-center">
                    <a href="#" class="btn btn-link btn-just-icon btn-twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="btn btn-link btn-just-icon btn-facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="btn btn-link btn-just-icon btn-gmail"><i class="fa fa-google-plus"></i></a>
                  </div>
                </div>
              </div>
            {% endfor %}
        </div>
      </div>
    </div>
    <div class="section landing-section">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <h2 class="text-center">Keep in touch?</h2>

            <form class="contact-form" method="POST"> {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                    {{ form.name|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.email|as_crispy_field }}
                </div>
              </div> <br>
                    {{ form.phone|as_crispy_field }} <br>

                    {{ form.message|as_crispy_field }}
              <div class="row">
                <div class="col-md-4 offset-md-4">
                  <button class="btn btn-danger btn-lg btn-fill" type="submit">Send Message</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}

templates/footer.html
{% url 'home' as home %}
{% url 'accounts:login' as login %}
{% url 'accounts:signup' as register %}

{% if request.path == home or request.path == login or request.path == register %}
    <div class="demo-footer text-center">
      <h6>&copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, made with <i class="fa fa-heart heart"></i> by <a href="https://www.geetechlab.com">Geetech Lab</a></h6>
    </div>
  </div>
</div>
{% else %}
    <footer class="footer footer-black footer-big">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-4 ml-auto mr-auto">
          <div class="logo text-center">
            <h3>NWABEN.COM</h3>
          </div>
        </div>
        <div class="col-md-6 offset-md-2 col-sm-8">
          <div class="links">
            <ul>
              <li>
                <a href="{% url 'home' %}">
                  Home
                </a>
              </li>
              <li>
                <a href="{% url 'about' %}">
                  About
                </a>
              </li>
              <li>
                <a href="{% url 'mp3:album_list' %}">
                  Music
                </a>
              </li>
            </ul>
            <hr />
            <div class="copyright">
              <div class="pull-left">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script>, made with <i class="fa fa-heart heart"></i> by <a href="https://www.geetechlab.com">geetechlab</a>
              </div>
              <div class="pull-right">
                <ul>
                  <li>
                    <a href="#">
                      Terms
                    </a>
                  </li>
                  |
                  <li>
                    <a href="#">
                      Privacy
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
{% endif %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}home{% endblock %}

{% block content %}

<div class="landing-page">
    <div class="wrapper">
      <div class="page-header" data-parallax="true" style="background-image: url('https://res.cloudinary.com/geetechlab-com/image/upload/v1612913404/nwaben.com/concert-768722_1280_mptdmy.jpg')">
        <div class="filter"></div>
        <div class="content-center">
            <!-- main website -->
          <div class="container">
            <div class="motto">
              <h3 class="title">THE NWAZURUOKE NWABEN FAMILY</h3>
              <h5 class="description">The Nwazuruoke NwaBen family <br>hails from Achina in Anambra state of Nigeria, West Africa.</h5>
{#                <h5 class="description">Let the memory of Nze EmmanuelMary<br> be with us forever</h5>#}
              <br/>
                <br/>
                <a href="{% url 'about' %}" type="button" class="btn btn-outline-neutral btn-round">Read More</a>
{#              <a href="{% url 'burial_memories:list' %}" type="button" class="btn btn-outline-neutral btn-round">Click to Write a Tribute</a>#}
            </div>

          </div>
            <!-- main website ends -->

{#            <div class="container mt-5">#}
{#                <div class="row">#}
{#                    <div class="col-md-5">#}
{#                        <img class="rounded img-thumbnail" style="height: 400px; width: 350px;"#}
{#                             src={{ burial_memory.image_url }}/>#}
{#                    </div>#}
{#                    <div class="col-md-6  ml-auto">#}
{#                        <h3 class="title">{{ burial_memory.get_name }} {% if burial_memory.other_names %}(#}
{#                            {{ burial_memory.other_names }}){% endif %} <br> {{ burial_memory.date_of_birth|date:'Y' }}#}
{#                            - {{ burial_memory.date_of_death|date:'Y' }}</h3>#}
                        {#                            <h5 class="description">{{ burial_memory.date_of_birth|date:'Y' }} - {{ burial_memory.date_of_death|date:'Y' }}</h5>#}
{#                        <blockquote class="blockquote">#}
                            {#                                <h6 >Let the memory of Nze EmmanuelMary be with us forever.</h6>#}
                            {#                                <hr style="width: 50%;">#}
{#                            <h5 class="description">Born on {{ burial_memory.date_of_birth }}#}
{#                                in {{ burial_memory.place_of_birth }}</h5>#}
{#                            <h5 class="description">Passed away on {{ burial_memory.date_of_death }}#}
{#                                in {{ burial_memory.place_of_death }}</h5>#}
{#                            <footer class="blockquote-footer" style="color: white">This website is administered by:#}
{#                                <cite title="Source Title">{{ burial_memory.by.get_full_name }}</cite></footer>#}
                            {#                                <h5 class="description">Details here...</h5>#}
{#                        </blockquote>#}
{#                        <br/>#}
{#                        <button id="share_memorial" class="btn btn-warning btn-round btn-lg">#}
{#                            <i class="fa fa-share-alt" aria-hidden="true"></i> Share Memory#}
{#                        </button>#}
{#                        <script>#}
{#                            let text_to_copy = document.URL;#}
{#                            let copy_button = document.getElementById("share_memorial");#}
{##}
{#                            copy_button.addEventListener("click", function () {#}
{#                                let temp = document.createElement("INPUT");#}
{#                                temp.value = text_to_copy;#}
{#                                document.body.appendChild(temp);#}
{#                                temp.select();#}
{#                                document.execCommand("copy");#}
{#                                temp.remove();#}
{#                                swal("Link Copied!", "You can go ahead and share this memory");#}
{#                            });#}
{#                        </script>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
        </div>
      </div>

{% endblock content %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %} | nwaben.com</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
          name='viewport'/>
    <!-- Extra details for Live View on GitHub Pages -->
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/paper-kit.min.css' %}" rel="stylesheet"/>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="{% static 'js/htmx.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'css/magnific-popup.css' %}" type="text/javascript"></script>
    {#        {% django_htmx_script %}#}
    {% block ext_css %}
    {% endblock %}
</head>

{% url 'home' as home %}

{% if request.path == home %}
    <body class="landing-page full-screen sidebar-collapse">
{% else %}
    <body>
{% endif %}
{% if messages %}
    {% for message in messages %}
        toastr.{{ message.tags }}("{{ message }}");
    {% endfor %}
{% endif %}
{% include "navbar.html" %}

{% block content %}
{% endblock content %}

{% include "footer.html" %}

<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}" type="text/javascript"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static 'js/plugins/moment.min.js' %}" type="text/javascript"></script>
<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="{% static 'js/plugins/bootstrap-tagsinput.js' %}" type="text/javascript"></script>
<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{% static 'js/plugins/bootstrap-selectpicker.js' %}" type="text/javascript"></script>
<!--	Plugin for Datetimepicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
<script src="{% static 'js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
<!--  Vertical nav - dots -->

<!-- Plugin for toast messages -->
{#        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>#}
<link rel="stylesheet" type="text/css" href="{% static 'css/toastr.min.css' %}" media="all">
<script type="text/javascript" src="{% static 'js/toastr.min.js' %}"></script>

<!--  Photoswipe files -->
<script src="{% static 'js/plugins/photo_swipe/photoswipe.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/photo_swipe/photoswipe-ui-default.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/photo_swipe/init-gallery.js' %}" type="text/javascript"></script>
<!--  for Jasny fileupload -->
<script src="{% static 'js/plugins/jasny-bootstrap.min.js' %}" type="text/javascript"></script>
<!-- Control Center for Paper Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/paper-kit.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/_hyperscript.js' %}" type="text/javascript"></script>
<script src="{% static 'js/magnific-popup.js' %}" type="text/javascript"></script>
<!--  Google Maps Plugin
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script> -->

{% block ext_js %}
{% endblock %}

<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5f243e3b4f3c7f1c910d9572/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->

</body>

</html>

templates/messages.html
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} alert-with-icon">
          <div class="alert-wrapper">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <i class="fa fa-times"></i>
            </button>
                <div class="message">
                  <i class="fa fa-bell"></i>
                  {{ msg }}
                </div>
          </div>
        </div>
    {% endfor %}
{% endif %}

{#<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">#}
{#  <div class="toast" style="position: absolute; top: 0; right: 0;">#}
{#    <div class="toast-header">#}
{#      <img src="..." class="rounded mr-2" alt="...">#}
{#      <strong class="mr-auto">Bootstrap</strong>#}
{#      <small>11 mins ago</small>#}
{#      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">#}
{#        <span aria-hidden="true">&times;</span>#}
{#      </button>#}
{#    </div>#}
{#    <div class="toast-body">#}
{#      Hello, world! This is a toast message.#}
{#    </div>#}
{#  </div>#}
{#</div>#}

templates/navbar.html
{% url 'home' as home %}
{% url 'about' as about %}
{% url 'articles:article_list' as article_list %}
{% url 'mp3:album_list' as album_list %}
{% url 'burial_memories:list' as memorial_list %}
{% url 'accounts:login' as login %}
{% url 'accounts:signup' as register %}
{% url 'accounts:profile' as profile %}


<!-- Navbar -->
{#{% if request.path == home or request.path == login or request.path == register or request.path == about or request.path == profile  or request.path == album_list or request.path == memorial_list %}#}
    <nav class="navbar navbar-expand-lg nav-down navbar-absolute navbar-transparent" color-on-scroll="500">
{#{% else %}#}
{#    <nav class="navbar navbar-expand-lg navbar-absolute nav-down">#}
{#{% endif %}#}
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="{% url 'home' %}" rel="tooltip" title="nwaben" data-placement="bottom" target="_blank">
          NWABEN.COM
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" data-nav-image="https://res.cloudinary.com/geetechlab-com/image/upload/v1612913403/nwaben.com/music-3888684_1280_gtqxnv.png" data-color="orange">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            {% if request.path == home %}
                <a href="{% url 'home' %}" class="nav-link  active">
                (-home-) <span class="sr-only">(current)</span> </a>
            {% else %}
                <a href="{% url 'home' %}" class="nav-link">home
                </a>
            {% endif %}
          </li>


          <li class="nav-item">
            {% if request.path == about %}
                <a href="{% url 'about' %}" class="nav-link  active">
                (-about-) <span class="sr-only">(current)</span> </a>
            {% else %}
                <a href="{% url 'about' %}" class="nav-link">about
                </a>
            {% endif %}
          </li>


          <li class="nav-item">
              {% if request.path == article_list %}
                <a href="{% url 'articles:article_list' %}" class="nav-link active">
                    (-blog-) <span class="sr-only">(current)</span> </a>
              {% else %}
                  <a href="{% url 'articles:article_list' %}" class="nav-link">blog</a>
              {% endif %}
          </li>

          <li class="nav-item">
              {% if request.path == album_list %}
                <a href="{% url 'mp3:album_list' %}" class="nav-link active">
                    (-music-) <span class="sr-only">(current)</span> </a>
              {% else %}
                  <a href="{% url 'mp3:album_list' %}" class="nav-link">music</a>
              {% endif %}
          </li>

        {% if request.user.is_authenticated %}
            <li class="dropdown nav-item">
                <a href="#paperp-kit" class="nav-link" data-toggle="dropdown">
                  <div class="profile-photo-small">
                    <img class="img-circle img-responsive img-no-padding" src="{{ user.image_url }}" alt="{{ user.username }}">
                  </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-danger" aria-labelledby="navbarDropdownMenuLink1">
                  <a class="dropdown-item" href="{% url 'accounts:profile' %}">
                    <i class="fa fa-user-circle"></i> profile
                  </a>
                  {% if request.user.is_superuser %}
                    <a class="dropdown-item" href="/admin-family-nwaben/">
                        <i class="fa fa-dashboard"></i> admin-dashboard
                    </a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                    <i class="fa fa-sign-out"></i> logout
                  </a>
                </div>
            </li>
        {% else %}
            <li class="dropdown nav-item">
                <a href="#" class="nav-link" data-toggle="dropdown">account</a>
                <div class="dropdown-menu dropdown-menu-right dropdown-danger" aria-labelledby="navbarDropdownMenuLink1">
                  <a class="dropdown-item" href="{% url 'accounts:login' %}">
                    <i class="fa fa-sign-in"></i> login
                  </a>
                  <a class="dropdown-item" href="{% url 'accounts:signup' %}">
                    <i class="fa fa-user-plus"></i> register
                  </a>
                </div>
            </li>
        {% endif %}

          <!-- <li class="nav-item">
					<a class="nav-link" rel="tooltip" title="Follow us on Twitter" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank">
						<i class="fab fa-twitter"></i>
						<p class="hidden-lg-up">Twitter</p>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" rel="tooltip" title="Like us on Facebook" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank">
						<i class="fab fa-facebook-square"></i>
						<p class="hidden-lg-up">Facebook</p>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" rel="tooltip" title="Follow us on Instagram" data-placement="bottom" href="https://www.instagram.com/CreativeTimOfficial" target="_blank">
						<i class="fab fa-instagram"></i>
						<p class="hidden-lg-up">Instagram</p>
					</a>
				</li> -->
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->